Feature/keyboard enhancements
smartdevicelink/generic_hmi pull request #348
Opened 2021-01-15 18:59 UTC by JackLivio

Fixes #181 
### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Core Tests
- Perform interaction keyboard with all layouts (numeric is new layout)
- Test behavior of masking global property
- Test behavior of setting custom keys on different layouts

Core version / branch / commit hash / module tested against:  Keyboard enhancements branch / 4e7603e604ec578c2aa5fa41784dce6ea5c60fb9
Proxy+Test App name / version / branch / commit hash / module tested against: Test suite master

### Summary
Adds support for a new layout: NUMERIC
Adds ability to mask the users input
Adds ability for mobile to set custom keys in place of special characters on the top level of the keyboard layout.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2021-01-25 15:49 UTC, jacobkeeler requested changes

2021-01-25 15:49 UTC, jacobkeeler commented on src/js/Keyboard.js
> +    var replaceableChars = '`-=[]\\;\',./^+#<&(_)=$:!@';
```suggestion
    var replaceableChars = '`-=[]\\;\',./^+#<&(_)$:!@';
```
Seems that `=` was included twice

2021-01-25 15:49 UTC, jacobkeeler commented on src/js/Keyboard.js
> +                </div>
```suggestion
                <div className="input-row">
                    <input
                        className="input-text"
                        value={this.state.input}
                        type={maskedInput ? "password" : "text"}
                        placeholder={"Tap on the virtual keyboard to start"}
                        onChange={this.onChangeInput}
                    />
                    <input 
                        className="mask-checkbox"
                        id="maskOption"
                        type={showUserMaskOption ? "checkbox" : "hidden"} 
                        onClick={this.handleUserMask}
                    />
                    <label 
                        for="maskOption" 
                        className="mask-checkbox mask-option-label"
                        style={{display: showUserMaskOption ? 'inline' : 'none' }}
                    >
                        Mask Input
                    </label>
                </div>
```

2021-02-10 20:48 UTC, jacobkeeler requested changes
Also, it looks like keyboard property changes do not take effect while the keyboard is active unless a button is pressed, which can be a bit jarring. I think that ideally the keyboard should update immediately if the keyboard properties are set while it is active.

2021-02-11 16:41 UTC, jacobkeeler commented on src/js/Controllers/UIController.js
> +
Nitpick

2021-02-11 16:47 UTC, jacobkeeler approved these changes

2021-02-11 16:48 UTC, JackLivio commented
For anyone wondering, we decided that a SetGlobalProperties should not change the keyboard layout while in view.

2021-02-12 14:13 UTC, merged