Add timer offset logic to handle RESUME event
smartdevicelink/generic_hmi pull request #349
Opened 2021-01-19 16:49 UTC by jacobkeeler

Fixes issue with #329 

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Core Tests
- Sending multiple PAUSE and RESUME events with different playback rates
- Sending multiple RESUME events in a row with different playback rates

Core version / branch / commit hash / module tested against: develop
Proxy+Test App name / version / branch / commit hash / module tested against: RPC Builder App JS, master

### Summary
Adds proper logic for resuming timer by storing the timer offset when a pause/resume event is received

### Changelog
##### Bug Fixes
* Fixes SetMediaClockTimer behavior when a RESUME event is received with a specific countRate

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2021-01-21 19:19 UTC, ShobhitAd requested changes

2021-01-21 19:19 UTC, ShobhitAd commented on src/js/reducers.js
> +                app.timerOffset = null
Wouldn't it be better to set the value to 0(instead of null) and directly use `app.timerOffset` in `MediaTrackInfo_c.js` and `ProgressBar_c.js`

2021-01-22 21:31 UTC, ShobhitAd approved these changes

2021-01-25 18:49 UTC, JulianKast approved these changes
Works with Java_Suite

2021-01-26 13:37 UTC, merged